-- =====================================================================
-- EazyPlanIA — V1__init.sql
-- Esquema inicial de la base de datos (8 tablas del modelo de dominio).
-- Generado para PostgreSQL 16.
-- Hibernate ddl-auto=validate requiere que este esquema coincida con las
-- entidades JPA. IDENTITY = GENERATED BY DEFAULT AS IDENTITY.
-- =====================================================================

-- ── users ────────────────────────────────────────────────────────────
CREATE TABLE users (
    id        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username  VARCHAR(255) NOT NULL UNIQUE,
    name      VARCHAR(255) NOT NULL,
    email     VARCHAR(255),
    password  VARCHAR(255),
    role      VARCHAR(255) NOT NULL
);

-- ── diets ────────────────────────────────────────────────────────────
CREATE TABLE diets (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL,
    name           VARCHAR(255) NOT NULL,
    description    VARCHAR(255),
    diet_type      VARCHAR(255) NOT NULL,
    start_date     DATE         NOT NULL,
    end_date       DATE,
    daily_calories REAL,
    daily_protein  REAL,
    daily_carbs    REAL,
    daily_fats     REAL,
    daily_water    REAL,
    CONSTRAINT fk_diets_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ── workouts ─────────────────────────────────────────────────────────
CREATE TABLE workouts (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL,
    start_time   TIMESTAMP(6),
    end_time     TIMESTAMP(6),
    workout_type VARCHAR(255),
    notes        VARCHAR(255),
    CONSTRAINT fk_workouts_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ── exercises ────────────────────────────────────────────────────────
CREATE TABLE exercises (
    id           BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_id   BIGINT         NOT NULL,
    name         VARCHAR(255),
    muscle_group VARCHAR(255),
    sets         INTEGER,
    reps         INTEGER,
    weight       DOUBLE PRECISION,
    completed    BOOLEAN,
    CONSTRAINT fk_exercises_workout FOREIGN KEY (workout_id) REFERENCES workouts (id)
);

-- ── grocery_lists ────────────────────────────────────────────────────
CREATE TABLE grocery_lists (
    id            BIGINT   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT   NOT NULL,
    created_at    DATE,
    is_purchased  BOOLEAN,
    CONSTRAINT fk_grocery_lists_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ── grocery_items ────────────────────────────────────────────────────
CREATE TABLE grocery_items (
    id              BIGINT   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grocery_list_id BIGINT   NOT NULL,
    name            VARCHAR(255),
    category        VARCHAR(255),
    quantity        INTEGER,
    unit            VARCHAR(255),
    purchased       BOOLEAN,
    organic         BOOLEAN,
    CONSTRAINT fk_grocery_items_list FOREIGN KEY (grocery_list_id) REFERENCES grocery_lists (id)
);

-- ── macro_logs ───────────────────────────────────────────────────────
CREATE TABLE macro_logs (
    id        BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT           NOT NULL,
    diet_id   BIGINT           NOT NULL,
    date      DATE,
    calories  DOUBLE PRECISION,
    protein   DOUBLE PRECISION,
    carbs     DOUBLE PRECISION,
    fats      DOUBLE PRECISION,
    CONSTRAINT fk_macro_logs_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_macro_logs_diet FOREIGN KEY (diet_id) REFERENCES diets (id)
);

-- ── micro_logs ───────────────────────────────────────────────────────
CREATE TABLE micro_logs (
    id        BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT           NOT NULL,
    date      DATE,
    sodium     DOUBLE PRECISION,
    potassium  DOUBLE PRECISION,
    magnesium  DOUBLE PRECISION,
    calcium    DOUBLE PRECISION,
    iron       DOUBLE PRECISION,
    vitaminc   DOUBLE PRECISION,
    CONSTRAINT fk_micro_logs_user FOREIGN KEY (user_id) REFERENCES users (id)
);
